spring.application.name=Ejercicio044

spring.datasource.url=jdbc:postgresql://ep-little-cell-apuzz2wf-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6zHxjpk3PIaX

spring.jpa.hibernate.ddl-auto=update